### ISSUE TITLE
Writing images with more than 8 channels

### ISSUE THREAD

**Issue by KarelPeeters** [johannesvollmer/exrs#102]
First of all thanks for making this crate, it's very useful and pleasant to use.

When the example [`4_specific_write.rs`](https://github.com/johannesvollmer/exrs/blob/c4a591f4b21580f5d4478455e7a28416ef770e80/examples/4_specific_write.rs) is changed so that the image contains more than 8 channels the code no longer compiles and instead results in the following error:

> the trait `IntoRecursive` is not implemented for `(exr::prelude::f16, f32, u32, f32, f32, f32, f32, f32, f32)`

This makes sense, indeed `IntoResursive` is only [implemented](https://github.com/johannesvollmer/exrs/blob/c4a591f4b21580f5d4478455e7a28416ef770e80/src/image/recursive.rs#L93-L101) for tuples up to size 8. In that file there's a comment saying

> // TODO use a macro to generate these impls!

Also, there's what looks to be an existing macro implementation at the bottom of the file. What was the blocker there? Was there an issue with the macro? Some other reason to not continue implementing this? If it's simply a time issue I'm willing to give it a shot and submit a PR.

In the meantime, does this crate currently have an existing workaround for this? In general, is it possible to write images with a number of channels or even a chanel data type not known at compile time?

**Comment by johannesvollmer** [comment]
Hi! Thank you for taking your time to open this issue. Your observations are correct, the trait is currently only implemented for up to 8 channels. The reason for this is that, frankly, I just couldn't get the macro working. If you want to try implementing said macro, I would gladly welcome a pulled request.

If not, don't worry, there is an alternative way of writing channels that makes no compile-time assumptions. This method allows you to write fully dynamic data. Have a look at this example: 

https://github.com/johannesvollmer/exrs/blob/c4a591f4b21580f5d4478455e7a28416ef770e80/examples/3_simple_write.rs#L56

With this approach, you can construct a `smallvec` containing any number of channels. Unfortunately, this currently requires you to allocate all samples of each channel in a separate vector. 

Keep me up to date, I'd like to know if this method works for you.

Also, please leave this issue open until the documentation is improved to point at this alternative method :)

**Comment by KarelPeeters** [comment]
Yep, that works great, thanks!

It's indeed a bit hard to find out about all of the features of this crate, the module level cargo doc page is a bit sparse and the examples are a lot of information at once, it's hard to tell which one contains the thing I'm actually looking for.

I'll fiddle around with the macro a bit over the next few hours to see if I can get it to work.

**Comment by KarelPeeters** [comment]
Okay I'm almost finished with the macro, but I started to wonder why the trait `IntoTuple` exists if `IntoNonRecursive` already exists. As far as I can tell we could just add an implementation like this and remove the current manual implementations of `IntoTuple`:

```rust
impl<I: IntoNonRecursive> IntoTuple<I::NonRecursive> for I {
    fn into_tuple(self) -> <I as IntoNonRecursive>::NonRecursive {
        self.into_non_recursive()
    }
}
```

It's not really guaranteed to be a tuple anymore but I don't think that fact ever actually gets used. Thoughts?

**Comment by johannesvollmer** [comment]
Great, nice work! 

Do you think a general `Exrs Book`, which would cover all the features once, would help?

> why the trait IntoTuple exists if IntoNonRecursive already exists

Yes, this sounds right. I think I tried that but it did not work the way I tried it, because of unrestricted parameters or some other orphan rule stuff. The reason we need to separate traits is because one trait can be asked to do a specific conversion by specifying a parameter and the other trait declares asingle associated output type.

If you find a way to simplify the two traits, try it! :)

**Comment by johannesvollmer** [comment]
For your PR, please prepare your changes in a new branch (e.g. "any size tuple macro") and then request a merge into the `dev` branch of this repository :)

**Comment by KarelPeeters** [comment]
Allright, I think it should be ready sometime tomorrow!

**Comment by johannesvollmer** [comment]
Oh cool, take your time :)

**Comment by johannesvollmer** [comment]
Hey, how is it going? Was is possible to code the macro? :)

**Comment by KarelPeeters** [comment]
Hey! Sorry for the delay, somehow this got lost in my todo-list.

I submitted #106, there are still some issues though which I wrote about there.

**Comment by johannesvollmer** [comment]
Actually,  @KarelPeeters, I'm still interested in what channels exactly you are writing :D I closed the pr before realizing

**Comment by KarelPeeters** [comment]
Ah you mean in terms of my use case?

I'm writing a raytracer and I'm writing extra debug information per pixel into the image, stuff like the amount of samples, the statistical variance in samples per pixel for each color, ...

You quickly get to quite a few channels this way!

**Comment by johannesvollmer** [comment]
Yes, thanks for the info. Also, thanks for the pull request! :) I'll put a new release on crates.io soon
