### ISSUE TITLE
Implement b44 

### ISSUE THREAD

**Issue by Narann** [johannesvollmer/exrs#104]
First, thanks for your hard work ! :)

As dumb it could seems, here is a plan proposal for adding b44 compression to exrs.

## Implement `b44ExpLogTable` program in rust

This program generate exponent and log value table for 16 bits floats: https://github.com/AcademySoftwareFoundation/openexr/blob/master/src/lib/OpenEXR/b44ExpLogTable.cpp

Generated file is then used in [ImfB44Compressor](https://github.com/AcademySoftwareFoundation/openexr/blob/master/src/lib/OpenEXR/ImfB44Compressor.cpp).

Current crate repository is not organized in a way it can contains multiple crates.

A way to do so is to have a main `Cargo.toml` with only `[workspaces]` section and multiple crates. Basically, move everything in `src/exrs/Cargo.toml`. The other way is to have another repo, but I think its overkill.

Question: Where to store this program and organize it's compilation?

## Implement `pack()` and `unpack##()`s

Before implement `compress()` and `uncompress()`, we need few functions. Biggest ones are:

* `pack()`
* `unpack14()`
* `unpack3()`

## Implement `Compressor()` constructor

[This part](https://github.com/AcademySoftwareFoundation/openexr/blob/master/src/lib/OpenEXR/ImfB44Compressor.cpp#L440) contains the library logic. `exrs` have its own so I would guess it will be the hardest part for newcomers.

## Implement  `compress()` and `uncompress()`

Those are the two where the rest of the compression logic is:

* [B44Compressor::compress()](https://github.com/AcademySoftwareFoundation/openexr/blob/master/src/lib/OpenEXR/ImfB44Compressor.cpp#L597)
* [B44Compressor::uncompress()](https://github.com/AcademySoftwareFoundation/openexr/blob/master/src/lib/OpenEXR/ImfB44Compressor.cpp#L839)

## Final

Anything I miss? Have I a good vision of what is left to do? Any corner case or difficulty I missed?

I can do the boring stuff and implement/rewrite each functions. The hardest part would be the the allocation part (Compressor constructor) as I don't know if it would need a rewrite in the way `exr` handle compressor data.

My last concern is about `b44ExpLogTable` program that would generate `b44ExpLogTable.rs` file. I suggest a reorganization of the repository:

```
Cargo.toml (1)
src/
    exrs/
        Cargo.toml (2)
    b44explogtable/
        Cargo.toml (3)
```

`(1)` would only contains:

``` yaml
[workspace]
members = ["src/exrs", "src/b44explogtable"]
```

`(2)` and `(3)` would respectively contains cargo information for individual lib and program.

What do you think?

**Comment by johannesvollmer** [comment]
Hi! Thanks for taking the time to investigate on the b44 compression method.

## Static Data Generation
> Generated file is then used in ImfB44Compressor.

Here's what I found out: The `.cpp` file you linked generates the source code for a header file. The [generated header file](https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr/e46ac0a70cad0d84f8e8be743a9b2d633056da5b/src/lib/OpenEXR/b44ExpLogTable.h) contains two generated `const unsigned short table[]`. 

So, in the end, what we need in this Rust library is just two simple `const TABLE: [u16; 1 << 16]`. Considering this, there might be no need to generate any file or restructure the crate, because it should be possible to simply `const fn` compute the array at compile time, like this (untested):

```rust
mod b44;

const TABLE: [u16; 1<<16] = generate_table();

const fn generate_table() -> [u16; 1<<16] {
    let mut table = [0; 1<<16];
    for (value, index) in table.iter_mut().enumerate() {
        *value = /* compute f16 based on index */;
    }
    table
}

pub fn compress(data: &mut[u8]){ ... }
pub fn decompress(data: &mut[u8]){ ... }
```

## Constructor Restructuring
> The hardest part would be the the allocation part (Compressor constructor) as I don't know if it would need a rewrite in the way exr handle compressor data.

Yes, this might turn out to be difficult. Up to this point however, we were able to convert all the compression methods constructors to a simple initialization within the method. I'd insist on trying that first, like it was done with the other compression methods, before restructuring the library.

The structural change I performed is: `new Compressor(parameters)->compress(data)` becomes `compress(parameters, data)`. As far as I could tell, the compressor object in the C++library is never used a second time, so there's no point in creating a dedicated object just to call a single method. 

## Tasks
> I can do the boring stuff and implement/rewrite each functions

That's awesome! I'm here if there are any questions or if you're stuck.

__Procedure__
Please keep in mind to avoid `unsafe` from the start. Other than that, first just make it work at all, and when it works, we can improve the working code. I recommend you create a roundtrip test, like [in the piz compressor](https://github.com/johannesvollmer/exrs/blob/c4a591f4b21580f5d4478455e7a28416ef770e80/src/compression/piz/mod.rs#L300).

And, as usual, please create a branch in your fork based on the `dev` branch, which can later be merged back into the `dev` branch.

**Comment by Narann** [comment]
Thanks for the information.

About the static data generation:

I just tried and it looks like `for` is not allowed in a `const fn`: https://doc.rust-lang.org/error-index.html#E0744

Seems to be possible using `#![feature(const_fn)]` but it's still unstable.

As you have the final file, another option would be to use it directly and generate its `.rs` equivalent. Not nice but this wouldn't require the need of a dedicated program.

**Comment by johannesvollmer** [comment]
Ah, I see. That's unfortunate. If you don't mind, I will try to find a work-around to try and generate it with a const fn. As far as I know, using a feature gate would render this whole crate unstable, which might be undesirable.

You can indeed just copy-paste the existing C++ header file and change the first few C++ lines to Rust (aswless as changing the file extension to `.rs`), and then include this file as a regular module in Rust. I think this will be an acceptable solution until `const fn` is stable enough :)

**Comment by johannesvollmer** [comment]
`const fn` will absolutely not work :D
The `while` loop works, with manually incrementing an integer. But floating point operations are not supported at all, meaning we cannot even multiply two floats at compile time (f16 is only storage, it uses f32 for arithmethic, so it will also not work).

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d392284303246cdb40ceb495fe7cdbcf)

**Comment by johannesvollmer** [comment]
There are other options however. We could also use lazy_static or use a macro instead. I'll try that

**Comment by Narann** [comment]
The "temporary" raw array copied from C++ header can be enough for now (I already did it in my repo). We could also have a commented implementation using the unstable feature so it will be ready for prime time.

**Comment by Narann** [comment]
It will not be easy. :-/

I have converted some code, but the "connection" with rest of the code will be harder.

Some terminologies doesn't seems to be the same (PixelType vs SampleType).

I can't find the `pLinear` property: https://github.com/AcademySoftwareFoundation/openexr/blob/e46ac0a70cad0d84f8e8be743a9b2d633056da5b/src/lib/OpenEXRUtil/ImfImageChannel.h#L44

This property is then use here: https://github.com/AcademySoftwareFoundation/openexr/blob/4c587457266cafb5d293d58963ec3c288fa4be2b/src/lib/OpenEXR/ImfB44Compressor.cpp#L503

The only I can find is `quantize_linearly`, but I suspect both doesn't represent the same (are they?).

The computation of the output buffer size is still a mystery between reference implementation and rust one. As an example. Buffer size for PIZ compression is computed like this in reference implementation:

https://github.com/AcademySoftwareFoundation/openexr/blob/e46ac0a70cad0d84f8e8be743a9b2d633056da5b/src/lib/OpenEXR/ImfPizCompressor.cpp#L160

But rust implementation simply use the uncompressed buffer / 3:

https://github.com/johannesvollmer/exrs/blob/master/src/compression/piz/mod.rs#L209

Damn, I've maybe be too greedy with this one. Both implementations are very different from each other. I will dig further, but maybe I'm just not comfy enough with rust yet.

**Comment by johannesvollmer** [comment]
The difference between the C++ and the Rust implementation are quite substantial. But keep in mind that every Rust version was quite similar to the C++ version in the beginning, and then we slowly simplified it further and further. You're looking at many hours of improving (and confusion). 

For example, for some compression methods, I only later realized that the size of the buffer is actually known, even if the C++ allocated a fixed amount. It's takes a good amount of trial and error to get it right, as you have already realized, but it's possible.

> quantize_linearly
Yes, it's the attribute your are looking for. The name `pLinear` is not easy to understand, so I renamed it slightly :)

**Comment by smaragden** [comment]
> The "temporary" raw array copied from C++ header can be enough for now (I already did it in my repo). We could also have a commented implementation using the unstable feature so it will be ready for prime time.

Another option could be to use a [build-script](https://doc.rust-lang.org/cargo/reference/build-scripts.html)  and generate the .rs files just before compiling.

**Comment by johannesvollmer** [comment]
Yes I thought that too, but it's just too wild. It's just a simple list of numbers and it does not deserve such a complicated process. Writing code that generates source code as string should not be necessary if all you want is a list of numbers. We'll wait for const fn.

**Comment by johannesvollmer** [comment]
> Buffer size for PIZ compression is computed like this in reference implementation: (link)
But rust implementation simply use the uncompressed buffer / 3

Oh wait yes you're right. I regret not putting a comment there. I guess the following happened: The output buffer in C++ has a fixed size that is always large enough. The fixed size is calculated based on the uncompressed size plus some extra bytes. This will always be enough, but most of the time more than enough. The piz compression will on average not need as much space as the uncompressed data. For the rare cases where more space is required, the Vec will just grow. Whether `uncompressed.len() / 3` is the optional  choice, is up to debate :) 

Again, these simplifications were made some time after the initial translation, and have been tested incrementally. You can absolutely do a 1:1 translation as a first step :) take some time, it will take a while

**Comment by Narann** [comment]
Thanks,

The copy part to the temp buffer seems to have much more branching than rust implementation. I would like to imitate it but I don't find how this can be achieve in rust `if (_format == XDR)`. exrs doesn't seems to have XDR handling in its "copy to tmp array" loops.

Am I missing something? Should I always consider `_format == XDR`? Or `_format != XDR`? Or raw copy paste the piz "copy to tmp" code? I suspect the logic is inside `lebe` crate and so, is omitted.

Thanks in advance.

**Comment by johannesvollmer** [comment]
>  I suspect the logic is inside lebe crate and so, is omitted.
That's exactly how it is handled in the other compression methods. However, I did not actually test the library on a big-endian system, so we don't know for sure whether this works. 

Can you link the exact lines of code you are talking about? Together we might find out how to handle the endianness in this case :)

**Comment by Narann** [comment]
Thanks, I will go with a brute approach for now. I just copy/pasted the piz implementation of "copy to tmp" and hope for the best:

https://github.com/johannesvollmer/exrs/blob/master/src/compression/piz/mod.rs#L182

My `compress()` implementation is compiling but I just realize I can't implement `decompress()` and compare results as B44 is lossy compression.

I suspect I will have to spend some times on a kinda hard coded test with real, bit perfect value comparisons.

**Comment by johannesvollmer** [comment]
I recommend you code an equality test with a tolerance, for example `original.iter().zip(decompressed).all(|(a,b)| (a-b).abs() < 0.1)` or something similar :)

**Comment by johannesvollmer** [comment]
Because the variable is called `xdr` and not `is_big_endian` or `is_opposite_endian`, we'll have to dig some more to find out what exactly the code should do (naming is hard but it's not impossible...)

**Comment by Narann** [comment]
Looks like I have compression working. Need to check the generated EXR on other software GIMP seems to open it. :)

It will be longer to have the decompress version (work, family). But if compression is working, it's a move in the good direction. :)

**Comment by johannesvollmer** [comment]
Awesome! From my experience, once you got the first one, the second one will be much easier and faster :) 

Of course, we can only merge when both ways work. And some more things need to be done after that, for example elaborate testing and maybe some simplifications. Furthermore, I am interested in finding out whether we can deduplicate some code across all compression methods in exrs.

**Comment by Narann** [comment]
I was able to make everything compile tonight. The result was wrong (compression is working but decompression is… meh…), I suspect it's related to `unpack14/3()` having many bit shifting all around. Still need investigation.

**Comment by johannesvollmer** [comment]
Awesome. Take your time. In my experience, when translating a compression method from C++, this debugging process will take quite some time, maybe more than you are used to. If you are stuck, I can have a look too :)

**Comment by johannesvollmer** [comment]
If you are stuck, just make sure you have pushed all changes to your fourth and then I'll pull it and have a look

**Comment by Narann** [comment]
I have actually finished yesterday: Generate an uncompressed file, save it (compress) in b44, open it (decompress) and save it in another uncompress.

Seems to work. I didn't do any in depth check but the way it's compressed make me think if it would have failed, it wouldn't work at all.

My last concern was about a weird behavior. I noticed some massive size drop in the second uncompressed file (I suspect it's related to F32 vs F16 but it shouldn't be any F32 here).

Anyway, I think you are right. I will make a dedicated, WIP branch so you can look into the code and test. Code is quite ugly at some place (not comfy with rust yet, especially for things you do quickly in C (`memcpy` for u8 to u16 and *vice versa*) but need to mess with slices.

**Comment by johannesvollmer** [comment]
Nice.

I used the `lebe` library for situations where C had a memcpy or an unsafe reinterpret cast. You can treat a byte vector as a file and use the `read` and `write` functions of that library on the vector

**Comment by johannesvollmer** [comment]
Like this one: https://github.com/johannesvollmer/exrs/blob/035ca67c977f83adcfb615094cad4d0307c32828/src/io.rs#L280

**Comment by johannesvollmer** [comment]
The default `exrs` tests will do a roundtrip test for all files in the project. If you enable your compression method, by removing the code which throws an error for all images with `B44` compression, you will get roundtrip tests for free:

https://github.com/johannesvollmer/exrs/blob/035ca67c977f83adcfb615094cad4d0307c32828/src/compression/mod.rs#L186

https://github.com/johannesvollmer/exrs/blob/035ca67c977f83adcfb615094cad4d0307c32828/src/compression/mod.rs#L224

**Comment by Narann** [comment]
I have done some modifications to enable compression/decompression and disable a `debug_assert` that check for result equality (because of lossy compression).

I'm messing with branches to push my work but get rejected by my own token because a new file need `workflow` permission:

```
! [remote rejected] dev -> dev (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/rust.yml` without `workflow` scope
```

So I need to regenerate a token. lol

**Comment by johannesvollmer** [comment]
> disable a debug_assert that check for result equality (because of lossy compression).

Oh right, I will change those tests to work with a threshold.

> workflow permission

I tried to get the github checks working. I think it still doesn't work. In the process I also might have made some changes to this file which causes the Problem you're describing. I'll investigate when I'm on the computer

**Comment by Narann** [comment]
No worry, I worked around the token problem and provide an PR for code review and advise: https://github.com/johannesvollmer/exrs/pull/112

**Comment by johannesvollmer** [comment]
Awesome. So the `workflows` file is not a  problem anymore?

**Comment by Narann** [comment]
Fixed by merged PR: https://github.com/johannesvollmer/exrs/pull/112
