### ISSUE TITLE
Compilation errors on benches code (unresolved imports)

### ISSUE THREAD

**Issue by Narann** [johannesvollmer/exrs#105]
Hello,

I suspect all files are not committed to the repository because I have few compilation errors.

Reproduce:

``` bash
git clone https://github.com/johannesvollmer/exrs.git
cd exrs
cargo build
```

Some content seems to be missing.

``` text
error[E0432]: unresolved imports `exr::image::full`, `exr::image::read_options`
 --> benches/read.rs:5:18
  |
5 | use exr::image::{full, read_options};
  |                  ^^^^  ^^^^^^^^^^^^ no `read_options` in `image`
  |                  |
  |                  no `full` in `image`
```

``` text
error[E0432]: unresolved import `exr::prelude::common`
  --> benches/write.rs:10:19
   |
10 | use exr::prelude::common::*;
   |                   ^^^^^^ could not find `common` in `prelude`
```

``` text
error[E0433]: failed to resolve: use of undeclared type `Compression`
  --> benches/write.rs:28:58
   |
28 |     for layer in &mut image.layers { layer.compression = Compression::ZIP1 };
   |                                                          ^^^^^^^^^^^ use of undeclared type `Compression`
```

The `dev` branch seems to have the same problems.

**Comment by johannesvollmer** [comment]
`exr::image::full` is an outdated struct. Where did you find this, on `dev` branch?! wait a minute I'll check it out

**Comment by johannesvollmer** [comment]
Ah, I see. This is the `benches` code. The benches are currently not used. However it's strange that I didn't update them. You can just ignore these for now, until they are updated. The error will not go away of course, instead of building the whole crate you can simply just run the tests (`cargo test`)

**Comment by johannesvollmer** [comment]
Leave this issue open, so that we can't forget to update the benches

**Comment by johannesvollmer** [comment]
I fixed the benchmarks and I can push them to `dev`

**Comment by Narann** [comment]
I confirm, it's fixed, thanks!
