### ISSUE TITLE
Implement TimeCode functions

### ISSUE THREAD

**Issue by Narann** [johannesvollmer/exrs#121]
Timecode is currently private:

https://github.com/johannesvollmer/exrs/blob/c4a591f4b21580f5d4478455e7a28416ef770e80/src/meta/attribute.rs#L107

There is a TODO to use fields instead of raw u32. I think we should keep this values as raw ints and implement TimeCode as original implemenation:

https://github.com/PetrVevoda/smallupbp/blob/master/OpenEXR/ImfTimeCode.h

**Comment by johannesvollmer** [comment]
I'm actually in the middle of implementing this, haha
