### ISSUE TITLE
Split compare_compression_content tests

### ISSUE THREAD

**Issue by Narann** [johannesvollmer/exrs#124]
## What can be improved or is missing?
For now, `compare_compression_content` is a single test containing a loop:

```rust
    for sub_dir in &["f32", "f16"] {
        let uncompressed_path = dir.join(sub_dir).join("uncompressed.exr");
        let mut uncompressed = read_first_flat_layer_from_file(uncompressed_path)
            .expect("uncompressed image could not be loaded");

        for image_name in &[
            "zip.exr", "zips.exr", "b44.exr", "b44a.exr",
            "dwaa.exr", "dwab.exr", "piz.exr", "rle.exr"
        ]{
```

It's the slowest test of all and I think tests should be short and specific to make debugging easier when one is failing.

## Implementation Approach

I suggest to separate them is respective tests:

* `zip_f32`
* `zip_f16`
* `zips_f32`
* `zips_f16`
* `b44_f32`
* `b44_f16`
* `b44a_f32`
* `b44a_f16`
* `dwaa_f32`
* `dwaa_f16`
* `dwab_f32`
* `dwab_f16`
* `piz_f32`
* `piz_f16`
* `rle_f32`
* `rle_f16`

This allow to identify failing case easily and you can call test for specific cases (something you often do when a test is failing):

```bash
cargo test --package exr --test across_compression
```

Of course, each individual test could use a shared function that took `compression` and `precision` argument.

In general, more test is slower to write than loops, but it makes test debugging easier.

Keep the good work!

**Comment by johannesvollmer** [comment]
merged into dev
