### ISSUE TITLE
Multiple public Blocks enums

### ISSUE THREAD

**Issue by Narann** [johannesvollmer/exrs#127]
Hello! :)

# Description

`exrs` have two `Blocks` enums:

* `exr::image::Blocks` in `image/mod:132`
* `exr::meta::Blocks` in `meta/mod:101`

The former is the one called by:

```rust
use exr::prelude::*;  // exr::image::Blocks
```

The latter is the one called by explicit:

```rust
use exr::meta::Blocks;
```

# Problem

This can bring to library misuse and confusion (you can import the bad Blocks when you want to use `exrs`).

# Suggestion

I understand why there are two different `Blocks` enum.

I suggest to rename `exr::meta::Blocks` to `exr::meta::BlockDescription`, with an explicit comment about it's metadata-only use.

What do you think about this?

**Comment by johannesvollmer** [comment]
Yes, absolutely. `BlockDescription` is perfect

**Comment by Narann** [comment]
Thanks, I will do a PR. on `master`, or `dev`?

**Comment by johannesvollmer** [comment]
always dev :) master is currently designed to be the same as the published crate
