### ISSUE TITLE
Debug assertion panicked in B44 code for an invalid image file

### ISSUE THREAD

**Issue by johannesvollmer** [johannesvollmer/exrs#135]
# Description
When reading the image file, the library panicked. It should return an error instead. The error was found by fuzzing.

# Reproducing

[the invalid image file](https://github.com/johannesvollmer/exrs/blob/dev/tests/images/fuzzed/fuzz_51_92-1-0-130-211-8-21-70-74-4-9-5-0-23-0-3-20-25-6-5-229-30-0-34-218-0-40-7-5-2-7-0.exr
)
[the code reading the image file](https://github.com/johannesvollmer/exrs/blob/4f2c78773041dfc54f127cd0dbefdd7d9358893b/tests/dev.rs#L83)
[the assertion in the b44 module that panicked](https://github.com/johannesvollmer/exrs/blob/4f2c78773041dfc54f127cd0dbefdd7d9358893b/src/compression/b44/mod.rs#L210)

# Notes
@narann Any idea what the issue could be?

**Comment by johannesvollmer** [comment]
Can't find any obvious mistake in the Rust translation around the unpack function call

**Comment by johannesvollmer** [comment]
Using `(13_u8.wrapping_shl(2))` instead of `13<<2` also does not help

**Comment by Narann** [comment]
The debug assertion ensure we are working on *kinda* valid data: https://github.com/AcademySoftwareFoundation/openexr/blob/master/src/lib/OpenEXR/ImfB44Compressor.cpp#L393

Looks like it's technically useless to ensure this. As you said, it's more restrictive than original condition. Interestingly your fuzing image would trigger the debug assert in original implementation if testing.

**Comment by johannesvollmer** [comment]
Thanks for checking! :) Then I'll just comment out the debug assert after adding a little comment. As the check is only done in debug mode, it won't be an issue in the original C++ code, I guess
