### ISSUE TITLE
Read and Write struct `SimpleImage`

### ISSUE THREAD

**Issue by johannesvollmer** [johannesvollmer/exrs#14]
Read and write an image without mip or rip levels, or deep data. Instead, have a simple struct that allows easier access and possibly filtered chunk access to avoid unnecessary allocation.

**Comment by johannesvollmer** [comment]
For example
```rust
SimpleImage {
  display_window: I32Box,
  parts: vec![
    Part {
      name: "Mask".into(),
      data_window: I32Box,
      channels: vec![
        Channel {
           name: "Luma".into(),
           pixels: Pixels::F16(data_vec),
           sampling: Vec2<usize>
        }
      ]
    }
  ]
}
```

**Comment by virtualritz** [comment]
I'm currently writing a direct-to-memory RenderMan display driver (actually for 3Delight) in Rust for some plug-in. For testing, I'm planning to make make a simplified version (which I'll open-source on GitHub) and make it spit out EXRs (so it's useful). Any chance for something like the above to work soonish? :)

**Comment by johannesvollmer** [comment]
Oh hey! There's a few things to be done before the first release. If we decide to postpone deep data for now, it won't take too long. Would that work out for you?

**Comment by virtualritz** [comment]
Yes, totally. I'm not planning to support writung fragments in a demo display driver. :)

**Comment by johannesvollmer** [comment]
Ok, I'll spend some time with it the next days. Stay tuned. There's a milestone for the first release, where you can check the progress :)

**Comment by virtualritz** [comment]
Beers! [The repo is here]([url](https://github.com/virtualritz/r-display)) btw.

**Comment by johannesvollmer** [comment]
Nice! I must admit, I'm not quite sure what exactly the capabilities of a display driver are. Does it render a scene file using Renderman? Will it display the rendered image in a window? :)

**Comment by virtualritz** [comment]
A display driver is a plug-in that gets pixels from a renderer. Then it does whatever it wants with them. E.g. write them to a file or show them in some window.

I am writing a direct-to-memory display driver in Rust for a project.

To test it I wrote a simplified version that outputs a file which in the repo I linked.
Ofc, all renderers implementing this API already ship with EXR display drivers.
So this is purely for educational purposes. No rush!

**Comment by johannesvollmer** [comment]
Thanks for the clarification! I think it won't be long to the first release. Would you like to try out a beta version before we release to crates.io?

**Comment by virtualritz** [comment]
Nah, go ahead. I'm happy to spend some hours this weekend though to switch the display driver to EXR support if there is code to work with.

**Comment by johannesvollmer** [comment]
I'm quite happy with what I got now, so I published it as a crate, yay!
[exr on crates.io](https://crates.io/crates/exr). If you encounter any problems or if the documentation is unclear, please do not hesitate to open an issue or comment here :)

As a quick start, have a look at [the examples](https://github.com/johannesvollmer/exrs/blob/master/examples/simple_write.rs). Beers! :D
