### ISSUE TITLE
Attempt to add/subtract with overflow in IntegerBounds::read

### ISSUE THREAD

**Issue by saethlin** [johannesvollmer/exrs#141]
# Description
Attempt to add/subtract with overflow in `IntegerBounds::read`, found with the image-rs/image exr fuzz target

# Reproducing
Produced using the fuzzer at https://github.com/image-rs/image/blob/0f1c38a97ec809f399a2a5edfb85c7e17fcd46ec/src/codecs/openexr.rs
This is one of the inputs that can cause a panic:
```
[118, 47, 49, 1, 34, 0, 0, 0, 105, 58, 47, 146, 146, 201, 0, 98, 111, 120, 255, 50, 39, 0, 0, 0, 0, 0, 7, 255, 255, 255, 255, 255, 255, 255, 255, 146, 201, 0, 98, 111, 120, 50, 105, 0, 43, 0, 0, 0, 222, 0, 255, 255, 255, 255, 255, 127, 255, 0, 255, 0, 111, 255, 255, 255, 255, 46, 2, 255, 122, 39, 1, 0, 0, 1, 0, 0, 8, 92, 255, 255, 255, 255, 255, 255, 255, 127, 255, 0, 255, 0, 111, 255, 255, 122, 39, 1, 0, 0, 0, 0]
```

I think the right thing here is to add a bunch of checked operations in the range calculation.

**Comment by johannesvollmer** [comment]
Thank you for the detailed report :)

**Comment by johannesvollmer** [comment]
Just pushed a new crates.io version of exrs. It works with the test data you provided, and I added some more unit tests and documentation. Time to update the version of exrs in the image-rs repository :)

see #142 
https://crates.io/crates/exr

**Comment by johannesvollmer** [comment]
I'm pretty confident that this update fixed the issue. If there any more test data from the fuzzing, it would be nice to add it? I've only used the one byte array from the issue description.

**Comment by saethlin** [comment]
I'm sure I could induce cargo-fuzz to emit more examples that trigger that overflow, but I'm not sure they're needed. Really all one gets from a fuzzer is examples, not other useful information; that is left to the humans.

**Comment by johannesvollmer** [comment]
Alright. Thanks again for the issue :)
