### ISSUE TITLE
Lack of big endian support

### ISSUE THREAD

**Issue by brad0** [johannesvollmer/exrs#155]
Trying to build ClamAV which seems to have some included Rust components including exr on OpenBSD/sparc64 fails like so..

```
   Compiling exr v1.4.2
error: expected `,`, found `function`
  --> /usr/ports/pobj/clamav-0.105.0/clamav-0.105.0/libclamav_rust/.cargo/vendor/exr/src/compression/rle.rs:39:29
   |
39 |         unimplemented!(this function probably returns little-endian data);
   |                             ^^^^^^^^ expected `,`

error: could not compile `exr` due to previous error
```

**Comment by johannesvollmer** [comment]
Yes, this is expected. This error appears as I could not test the library on a big-endian device, I assumed it would be better to fail at compile time than at runtime. Do you have the big endian device at hand? 

Note: If exr is included due to the image crate, it can be disabled temporarily by disabling the exr feature.

**Comment by brad0** [comment]
I don't, but other OpenBSD developers do. What exactly are you looking for?

**Comment by robinduerhager** [comment]
It seems like [QEMU can emulate SPARC Systems](https://wiki.qemu.org/Documentation/Platforms/SPARC). Maybe this could be a little more accessible for testing purposes. Also a CI Pipeline for Big-Endian compilation could be of interest in the future? The WASM3 Project seems to achieve good results with QEMU and GitHub Actions according to [this](https://github.com/wasm3/wasm3/issues/125#issuecomment-612995478).

**Comment by johannesvollmer** [comment]
GitHub doesn't support big endian platforms, but installing QEMU on an Ubuntu within a GitHub action didn't cross my mind. This is absolutely beautiful. See [tests.yml](https://github.com/wasm3/wasm3/blob/main/.github/workflows/tests.yml#L318). Thanks for pointing me to this approach :)

**Comment by robinduerhager** [comment]
no problem :D! However i think it would be better to use a local QEMU - Big Endian Instance for local development and testing purposes when specifically developing for big endian, while the GitHub Actions QEMU solution can be seen as an integration / security gateway for the repository.

**Comment by johannesvollmer** [comment]
It seems more complicated to run it locally than to use GitHub actions. Rebooting and installing all the stuff -

**Comment by johannesvollmer** [comment]
(oops closed accidentally due to sausage fingers)

It seems that getting it to run locally would be so much more effort than preparing the GitHub action. Why go through all the hassle: rebooting, installing more software, finding out all the necessary steps in the first place?

**Comment by robinduerhager** [comment]
Well it would be a question of how frequently you'd have to work on big endian code specifically. If i would have to work often on this, i would probably get a local testing environment to work so i keep my commit history clean. Although, If these problems just arise rarely, than a local testing environment is more optional i guess.

**Comment by mherrb** [comment]
FWIW, the compile farm project is providing shell access to a number of different machines with various CPU architectures and operating systems to help free software developers with testing on non-standard systems.
https://cfarm.tetaneutral.net/ 
There are some BE machines in the list of machines https://cfarm.tetaneutral.net/machines/list/

**Comment by johannesvollmer** [comment]
Very interesting indeed!

**Comment by johannesvollmer** [comment]
A came quite far with the github actions qemu approach. However, even though the action passes, the tests are not actually run yet. The problem is currently that the generated binaries have unpredictable names and therefore cannot be referenced directly, forcing us to find all files with a specific prefix.

Current approach:
- [x] use ubuntu host machine
- [x] install qemu
- [x] cross-build the Rust code for sparc64
- [x] cross-build the tests into a standalone executable for sparc64
- [ ] run the generated executables in qemu

See #157

**Comment by johannesvollmer** [comment]
Great news, using cross-rs it simply works out of the box for mips-unknown-linux-gnu. Not yet for sparc64-unknown-linux-gnu, but it should not be a problem

**Comment by brad0** [comment]
Any further progress on this?

**Comment by johannesvollmer** [comment]
I added quite a good number of tests. Everything seems to work except for one compression method, PXR24. No matter what I try, it would not work on big endian.

So, if someone else has a look at the currently open PR, they might find the issue. Alternatively, we could merge the pr and accept that PXR24 will not be supported on big endian for now, returning an error instead.

**Comment by brad0** [comment]
> I added quite a good number of tests. Everything seems to work except for one compression method, PXR24. No matter what I try, it would not work on big endian.

Thanks. That is great.
 
> So, if someone else has a look at the currently open PR, they might find the issue. Alternatively, we could merge the pr and accept that PXR24 will not be supported on big endian for now, after adjusting it to return an error instead.

I think having some support would be better than nothing at all. It can be further refined going forward.

**Comment by brad0** [comment]
With that being the case is there anything holding back commiting what you have at the moment?

**Comment by johannesvollmer** [comment]
No, nothing particular, just the lack of time spent on the computer. I will try to get a few things done on the computer tomorrow, hopefully also this :)

**Comment by brad0** [comment]
Thank you.

**Comment by johannesvollmer** [comment]
updating exr version in the image crate, see https://github.com/image-rs/image/pull/1771
