### ISSUE TITLE
Use `miniz_oxide` instead of `inflate`

### ISSUE THREAD

**Issue by Shnatsel** [johannesvollmer/exrs#161]
[`miniz_oxide`](https://crates.io/crates/miniz_oxide) is fast, mature and well-tested DEFLATE implementation in 100% safe Rust. 

The `png` crate has migrated from the  `inflate` crate to `miniz_oxide` a while ago, which got them multi-factor speedups.

I have extensively tested and fuzzed both implementations, so I am fairly confident in the robustness of both - but `miniz_oxide` is several times faster than `inflate`.

**Comment by johannesvollmer** [comment]
Excellent. I believe we currently use two separate crates, one for encoding and one for decoding. It might be possible to replace both dependencies

**Comment by johannesvollmer** [comment]
release should come soon, thanks for the suggestion

**Comment by johannesvollmer** [comment]
Here is a rough comparison of runtime speeds. Those are the benchmarks in the repository, might not be 100% accurate.


previously:
```
old baseline read_single_image_uncompressed_from_buffer_rgba ... bench:  40,662,980 ns/iter (+/- 6,833,197)
old baseline read_single_image_uncompressed_rgba             ... bench:  50,961,100 ns/iter (+/- 6,009,090)
old baseline write_uncompressed_to_buffered                  ... bench:  30,099,710 ns/iter (+/- 5,402,125)

old 1 core read_single_image_non_parallel_zips_rgba          ... bench: 340,530,460 ns/iter (+/- 15,852,589)
old 12 core read_single_image_zips_rgba                      ... bench:  89,947,160 ns/iter (+/- 16,587,139)

old 1 core write_nonparallel_zip1_to_buffered                ... bench: 460,181,240 ns/iter (+/- 61,940,510)
old 12 core write_parallel_zip16_to_buffered                 ... bench: 106,569,270 ns/iter (+/- 8,416,554)
old 12 core write_parallel_zip1_to_buffered                  ... bench: 110,876,530 ns/iter (+/- 14,531,352)
```

after switching to miniz_oxide & fixing for big endian platforms:
```
new baseline read_single_image_uncompressed_from_buffer_rgba ... bench:  39,681,070 ns/iter (+/- 7,085,556)
new baseline read_single_image_uncompressed_rgba             ... bench:  49,398,140 ns/iter (+/- 8,671,790)
new baseline write_uncompressed_to_buffered                  ... bench:  29,658,070 ns/iter (+/- 5,296,580)

new 1 core read_single_image_non_parallel_zips_rgba          ... bench: 207,590,860 ns/iter (+/- 10,638,892)
new 12 core read_single_image_zips_rgba                      ... bench:  66,450,130 ns/iter (+/- 17,860,443)

new 1 core write_nonparallel_zip1_to_buffered                ... bench: 527,988,470 ns/iter (+/- 18,740,436)
new 12 core write_parallel_zip16_to_buffered                 ... bench: 138,215,100 ns/iter (+/- 12,572,098)
new 12 core write_parallel_zip1_to_buffered                  ... bench: 122,700,490 ns/iter (+/- 14,102,269)
```

__Reading__ speed increased, by a factor of two if you cannot use multi threading. Of course, with more cores, this becomes less observable.

__Writing__ speed decreased, this might be because the level of compression was changed from `deflate::FAST` to `miniz_oxide level 4 of 10`, now probably using more time for a better compression. The compression ratio increased probably, I didn't check it.
