### ISSUE TITLE
Multiply with overflow

### ISSUE THREAD

**Issue by anfedotoff** [johannesvollmer/exrs#165]
Hi!
We were using our tool Sydr to find some integer overflows and we found this at [line](https://github.com/johannesvollmer/exrs/blob/master/src/meta/attribute.rs#L1503): 
`thread '<unnamed>' panicked at 'attempt to multiply with overflow', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/exr-1.5.0/src/meta/attribute.rs:1503:45`

Technically it is a true positive, but allocation is safe. Maybe after values `width` and `height` will be used and something can go wrong?

**Comment by johannesvollmer** [comment]
Thanks for the efforts! :) Do you have any more information? The input data, maybe? Or the code calling into the library?

**Comment by johannesvollmer** [comment]
As this is just the preview image, this is only the case for a corrupted image file. It should not panic or overflow of course. We can simply make these multiplications safe, using checked multiplications. I'm sure this will already solve the issue.

**Comment by anfedotoff** [comment]
> Thanks for the efforts! :) Do you have any more information? The input data, maybe? Or the code calling into the library?

:) We were fuzzing image-rs using this [harness](https://github.com/image-rs/image/blob/master/fuzz/fuzzers/fuzzer_script_guess.rs).  I attach the input file
[crash-sydr_8e195a006d8b5f59f3f0de7cb7e2a0f2e5b62843_int_overflow_0_unsigned.txt](https://github.com/johannesvollmer/exrs/files/9540017/crash-sydr_8e195a006d8b5f59f3f0de7cb7e2a0f2e5b62843_int_overflow_0_unsigned.txt)

**Comment by anfedotoff** [comment]
> As this is just the preview image, it will never be this large, except for the case of corrupted image files. Of course, for these cases, it should never overflow. We can simply make these multiplications safe, using checked multiplications. I'm sure this will already solve the issue.

Good, I try to compose a PR than!

**Comment by johannesvollmer** [comment]
That would be amazing!
