### ISSUE TITLE
Port from threadpool to rayon

### ISSUE THREAD

**Issue by notgull** [johannesvollmer/exrs#199]
## What can be improved or is missing?
The `threadpool` crate is no longer maintained. Meanwhile, `rayon` is not only much better maintained, but also supports using custom functions for spawning threads.

## Implementation Approach
We could replace the usage of `threadpool` with `rayon::spawn` et al. Since `threadpool` is in the public API, this is a breaking change.

**Comment by johannesvollmer** [comment]
the initial implementation was using rayon, but it had a few limitations, so we had to roll our own. it's been a while, but i think these were the problems:

- we collect the blocks from the parallel threads into one single image buffer that can can not be shared or sent across threads
- processing blocks must be streaming, meaning there should not be a huge vector with all the blocks at any time. instead the blocks should be read from the file and written to the image buffer on the fly

**Comment by notgull** [comment]
> of course, you can simply add rayon and not use the iterator based api. but the decision was made to not use rayon because of it's size. 

You can use the [`rayon-core`](https://docs.rs/rayon-core/latest/rayon_core/) package instead, which cuts out nearly all  of the cruft involved with Rayon and exposes a thread pooling API.

> does rayon have a mechanism to detect whether multi threading is available?

The best strategy is probably to have a `threading` feature that can be disabled if the user is on a platform without multithreading (e.g. WASM). I can implement this if you want.

**Comment by johannesvollmer** [comment]
Thanks for offering your help! We're actually in the middle of discussing that in another issue, see #200

i think the developer experience is better when using the crate will not crash out of the box. for that reason, i think it would be great to not fail at runtime, but instead fallback to the single-threaded code, that is already there. as there is an automatic solution, why should we ask the users of the library to go an manually switch that crate feature :)
