### ISSUE TITLE
This file cannot be opened

### ISSUE THREAD

**Issue by fursund** [johannesvollmer/exrs#202]
https://github.com/johannesvollmer/exrs/blob/66a247789004d974043300daf7bfc57c7d52a459/src/compression/mod.rs#L200

We're hitting in issue where channels are mixed between half and float, and it seems it might fail at this particular line of code?

**Comment by johannesvollmer** [comment]
Hi! Interesting. Can you provide the file?

Mixing the channel types is tested in the library, so I would like to have a look whether anything else might be the problem :)

**Comment by fursund** [comment]
https://drive.google.com/file/d/1dM0mpZXaMoAAZQCipFC0-7_hQ3t65wSM/view?usp=sharing

**Comment by johannesvollmer** [comment]
Thanks! I'll have a look :)

**Comment by fursund** [comment]
Thanks! It worked before miniz introduction in the lib.

**Comment by johannesvollmer** [comment]
You mean, before using the `zune-inflate` dependency for decompression (#183)? Or before using `miniz-oxide` (#162)?

**Comment by fursund** [comment]
Before miniz-oxide https://github.com/johannesvollmer/exrs/pull/162

**Comment by johannesvollmer** [comment]
Interesting. Good to know.

**Comment by johannesvollmer** [comment]
You think the expected byte size is calculated incorrectly? What error does it result in?

**Comment by fursund** [comment]
Error is: "thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Invalid("compressed ZIP1 data (invalid: zlib-compressed data malformed)")'". Yeah my guess was that the expected byte size was wrong.

**Comment by fursund** [comment]
If I remove ".set_limit(expected_byte_size)" here: https://github.com/johannesvollmer/exrs/blob/66a247789004d974043300daf7bfc57c7d52a459/src/compression/zip.rs#L22 then it works

**Comment by johannesvollmer** [comment]
some findings:
- the error from zune-inflate is `Output limit exceeded, set limit was 393216 and output size is 392539`
- (as you said) removing `set_limit` on zlib no longer returns an error
- after decompressing with zune-inflate, the size is checked later, in `decompress_image_section`
    https://github.com/johannesvollmer/exrs/blob/66a247789004d974043300daf7bfc57c7d52a459/src/compression/mod.rs#L232
- the size check later succeeds, which means zune-inflate returned the correct number of bytes after all

conclusion:
the data is decompressed to the correct size, but zune-inflate reports an error when a limit is set to that correct size.

**Comment by johannesvollmer** [comment]
here's the raw bytes of the zlib-compressed data:
[zlib-compressed-binary 393216 bytes.zip](https://github.com/johannesvollmer/exrs/files/10901054/zlib-compressed-binary.393216.bytes.zip)

**Comment by johannesvollmer** [comment]
here's the compressed data blob which results in the error: [zlib-compressed-binary 393216 bytes.zip](https://github.com/johannesvollmer/exrs/files/10901095/zlib-compressed-binary.393216.bytes.zip)

**Comment by johannesvollmer** [comment]
asked for help from our friends at zune-deflate

**Comment by johannesvollmer** [comment]
they fixed in incredibly fast, it's already online! be sure to run `cargo update` and then check whether it works now :)

**Comment by fursund** [comment]
great thanks!

**Comment by johannesvollmer** [comment]
awesome, thanks!
