### ISSUE TITLE
Failed unzipping EXR

### ISSUE THREAD

**Issue by fursund** [johannesvollmer/exrs#210]
Tried loading this EXR with 1.5.3 and it fails unzipping: https://drive.google.com/file/d/1JNZJtrko3U50p5B4e0figjqFOWiQDjFj/view?usp=sharing

**Comment by johannesvollmer** [comment]
Thanks for sharing! :) I'll have a look

**Comment by johannesvollmer** [comment]
Unfortunately there is no such mechanism in place right now

**Comment by etemesi254** [comment]
Hi, fixed. 

And updated, should happen transpalently

**Comment by fursund** [comment]
Great thanks!

**Comment by etemesi254** [comment]
And sorry for the bug

Wish we could all write perfect software :)


But would love to ask for permission to add the specific zip file into the test harness to catch  such cases in the future

**Comment by fursund** [comment]
Ah no worries! Thanks for fixing so promptly! No problem if you use the data as test case!

**Comment by Shnatsel** [comment]
I believe this issue is fixed and should be closed.

**Comment by johannesvollmer** [comment]
Yes. We could always reopen it if necessary.
