### ISSUE TITLE
Any plans for convenience methods?

### ISSUE THREAD

**Issue by mandeep** [johannesvollmer/exrs#29]
Hi @johannesvollmer. Thanks for the fantastic work on making a simple exr library for Rust developers.

I wrote an HDR image viewer as I couldn't find any decent FOSS ones in the Debian package repository. I'm in the process of adding your exr crate to my project, and I found that I'm writing a lot of wrappers around your library (F32 -> u8, resize, etc). Are there any plans to add these kind of convenience methods to the exr crate? If you want I can try submitting a PR for the things I've implemented.

**Comment by johannesvollmer** [comment]
Hi @mandeep, thanks for your interest.

Exrs aims to be convenient regarding reading and writing openexr files. However, it's currently not in the scope of this library to do complex image processing. Please tell me more about what functions exactly you missed in the library.

**Comment by johannesvollmer** [comment]
Also, please be aware that one of the most commonly used compression methods,  PIZ, is not supported yet.

**Comment by mandeep** [comment]
Thanks for letting me know about the missing compression methods. I'll try to submit some PRs for them if I'm able to find time. 

I thought about things some more and I currently like how minimal the `exr` crate is. I think image processing should be left to another library.

**Comment by johannesvollmer** [comment]
Cheers! Let me know if you have more questions or need help.
