### ISSUE TITLE
exr::Error should have a default formatter and impl std::error::Error

### ISSUE THREAD

**Issue by mandeep** [johannesvollmer/exrs#37]
`exr::Error` should have a default formatter so that `eprintln!("{}, error");` will work.

Also, `exr::Error` should impl `std::error::Error` that way you can return from a function as `Result<(), Box<dyn Error>`. 

If you would like help with this let me know and I will submit a PR.

**Comment by johannesvollmer** [comment]
Thanks for the issue. Sounds like a good idea. Can you nevertheless please show me some example usage of the new features you suggested? Why exactly is it important to implement them?

If you are curious, try to implement it yourself. The error type is defined inside `src/error.rs`. If any change outside of that Module is necessary, please let me know before you start working.

**Comment by mandeep** [comment]
The main reason is for error propagation. When you have a `main()` function that can error out in many ways, it helps when all of the functions that return `Result` do so with `std::error::Error` implemented for the `Err`. That way we can write a function prototype like `fn main() -> Result<(), Box<dyn Error>` and not have to worry about the different types of errors that different libraries return.

**Comment by johannesvollmer** [comment]
Ok, perfect. If you want to, do it. Also, feel free to ask anything here, especially if there's something that lacks documentation or otherwise needs more explanation in the library :)

**Comment by johannesvollmer** [comment]
fixed by #39
