### ISSUE TITLE
Consider incrementing minor version

### ISSUE THREAD

**Issue by mandeep** [johannesvollmer/exrs#48]
v0.7.4 broke a couple of applications as they are pinned to 0.7. Would it be possible to increment the minor version to 0.8.0? Not sure if this requires a removal of 0.7.4, mostly because I have no clue how crate yanks work.

**Comment by johannesvollmer** [comment]
Unfortunately, this won't be the last breaking change. Although Rust crates use semantic versioning, this crate is still not considered stable - it's not yet version `1.0`. I want this library to support all compression methods before going version `1.0`.

What problems have you encountered when explicitly using version `0.7.3` (or earlier) in your `cargo.toml`?

**Comment by mandeep** [comment]
0.7.3 was fine, but I would expect 0.7.4 to be a backward compatible release regardless if the crate follows semver.

**Comment by johannesvollmer** [comment]
Ah yes! That is indeed how SemVer works, for stable crate. But as this crate is still not stable (not yet `1.0`), breaking changes are to be expected at any change of version, as described in SemVer. 

I would love to be `1.0` soon, but currently I have limited time and implementing the Piz Compression is not straight forward (see the piz branch).

**Comment by johannesvollmer** [comment]
I plan to do no further breaking changes, and focus on implementing the compression methods first, then going 1.0, which would finally make versioning something for you to rely on - but I don't think yanking is worth the trouble right now, so I'm going to leave the current version as is, I hope that's okay for now :)
