### ISSUE TITLE
Not working link

### ISSUE THREAD

**Issue by Hscowef** [johannesvollmer/exrs#77]
It is not a big deal but in `exrs\examples\README.md` the link for Version 0.7.5 is not working.[https://docs.rs/crate/exr/0.7.5/source/examples/](url)

**Comment by johannesvollmer** [comment]
Thanks for the issue! Currently, we are in the process of releasing `0.7.5`, sorry for the inconvenience. The next release will not be done in the master branch :D

**Comment by johannesvollmer** [comment]
(the release took longer than expected)

**Comment by Hscowef** [comment]
Oh ok sorry for the disturbance then :)

**Comment by johannesvollmer** [comment]
Don't worry, it's my fault. Cheers!

**Comment by johannesvollmer** [comment]
The new version is finally there, all links should work now. Check it out, there are a lot of improvements :)
