### ISSUE TITLE
Add more image/layer attributes

### ISSUE THREAD

**Issue by virtualritz** [johannesvollmer/exrs#90]
Missing (for me) `near`, `far`, `fieldOfViewHorizontal`, `fieldOfViewVertical`, `software`. 

For reference an `exrheader` dump of an EXR created by 3Delight:
```
file test_output_3dl.exr:

file format version: 2, flags 0x0
channels (type chlist):
    A, 16-bit floating-point, sampling 1 1
    B, 16-bit floating-point, sampling 1 1
    G, 16-bit floating-point, sampling 1 1
    N_camera.X, 16-bit floating-point, sampling 1 1
    N_camera.Y, 16-bit floating-point, sampling 1 1
    N_camera.Z, 16-bit floating-point, sampling 1 1
    R, 16-bit floating-point, sampling 1 1
compression (type compression): zip, multi-scanline blocks
dataWindow (type box2i): (0 0) - (639 479)
displayWindow (type box2i): (0 0) - (639 479)
far (type float): 1e+38
fieldOfViewHorizontal (type float): 45.6036
fieldOfViewVertical (type float): 35
lineOrder (type lineOrder): increasing y
near (type float): 0.001
pixelAspectRatio (type float): 1
screenWindowCenter (type v2f): (0 0)
screenWindowWidth (type float): 1
software (type string): "3Delight 2.1.23 darwin-x86_64 (Aug 17 2020, f7230f) "Re-Animator""
type (type string): "scanlineimage"
worldToCamera (type m44f):
   (1 0 0 0
    0 1 0 0
    0 0 1 0
    0 0 0 1)
worldToNDC (type m44f):
   (2.3787 0 0 0
    0 3.17159 0 0
    0 0 1 1
    0 0 -0.001 0)
```

**Comment by johannesvollmer** [comment]
Didn't you already create this issue some time ago?

**Comment by johannesvollmer** [comment]
Aaaaahh I see the changes were merged into master, but no release was published to crates.io :o

**Comment by virtualritz** [comment]
Ahh, sorry, I thought I did but then I thought I was hallucinating and didn't check closed issues. :D

I think `software` is still missing though?

**Comment by johannesvollmer** [comment]
Let me check that (maybe only tomorrow, if I can't find the time today)

**Comment by johannesvollmer** [comment]
https://github.com/johannesvollmer/exrs/blob/ad472beb19d5509654d7d6be3db6d49cfdcce7b6/src/meta/header.rs#L225-L237

There they are, including `software_name` :) 
So the only thing left to do is publishing to crates.io

**Comment by johannesvollmer** [comment]
```
 /// The field of view angle, along the horizontal axis, in degrees. 
 pub vertical_field_of_view: Option<f32>, 
```

Oh, there's a documentation error

**Comment by johannesvollmer** [comment]
Just pushed a [new version](https://github.com/johannesvollmer/exrs/releases/tag/v0.9.0) to crates.io. That one should contain the attributes, finally

**Comment by johannesvollmer** [comment]
Close this Issue if this works as expected :)

**Comment by virtualritz** [comment]
Yes, my EXR headers now match the ones I get from 3Delight's own EXR display driver. Cool!
